// PDF Renderer for Social Command Reports
// Uses @react-pdf/renderer to generate branded PDF documents from enriched report JSON.
// Mirrors the web ReportViewer layout: KPIs -> Executive Summary -> Charts -> Sentiment -> Top Content -> Recommendations

import React from 'react';
import {
  Document, Page, View, Text, Image, StyleSheet, Font, renderToBuffer,
} from '@react-pdf/renderer';
import path from 'path';
import fs from 'fs';

// ============================================================
// FONT REGISTRATION (module scope -- runs once)
// ============================================================

const fontDir = path.join(process.cwd(), 'public/brand/fonts');

Font.register({
  family: 'SharpGrotesk',
  src: path.join(fontDir, 'SharpGroteskSmBold21.otf'),
});

Font.register({
  family: 'PlusJakartaSans',
  fonts: [
    { src: path.join(fontDir, 'PlusJakartaSans-SemiBold.ttf'), fontWeight: 600 },
    { src: path.join(fontDir, 'PlusJakartaSans-Bold.ttf'), fontWeight: 700 },
  ],
});

// Disable hyphenation for cleaner text
Font.registerHyphenationCallback((word) => [word]);

// ============================================================
// BRAND CONSTANTS
// ============================================================

const BRAND = {
  purple: '#5B56F5',
  black: '#1A1B22',
  bone: '#F2F2F2',
  concrete: '#9CADBB',
  sienna: '#EF8260',
  slateBlue: '#B2C5D5',
};

// ============================================================
// STYLES
// ============================================================

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    paddingTop: 60,
    paddingBottom: 50,
    paddingHorizontal: 40,
    color: BRAND.black,
  },
  headerBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: BRAND.purple,
  },
  header: {
    position: 'absolute',
    top: 12,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTop: '1 solid #E5E7EB',
    paddingTop: 8,
  },
  kpiRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  kpiCard: {
    flex: 1,
    backgroundColor: BRAND.bone,
    borderRadius: 4,
    padding: 10,
  },
  sectionTitle: {
    fontFamily: 'SharpGrotesk',
    fontSize: 14,
    marginBottom: 8,
    marginTop: 16,
    color: BRAND.black,
  },
  chartImage: {
    width: '100%',
    marginTop: 8,
  },
  recommendationRow: {
    marginBottom: 8,
    flexDirection: 'row',
    gap: 6,
  },
  sentimentCard: {
    marginBottom: 6,
    padding: 8,
    backgroundColor: BRAND.bone,
    borderRadius: 4,
  },
});

// ============================================================
// KPI VALUE FORMATTING
// ============================================================

function formatKPIValue(kpi) {
  const v = kpi.value;
  if (v == null) return '\u2014';
  switch (kpi.format) {
    case 'number':
      return typeof v === 'number' ? v.toLocaleString() : String(v);
    case 'percent':
      return `${v}%`;
    case 'delta':
      return `${v > 0 ? '+' : ''}${v}`;
    case 'text':
      return String(v);
    default:
      return typeof v === 'number' ? v.toLocaleString() : String(v);
  }
}

function formatDelta(delta) {
  if (delta == null) return null;
  const sign = delta > 0 ? '+' : '';
  return `${sign}${delta}%`;
}

// ============================================================
// REPORT PDF COMPONENT
// ============================================================

export function ReportPDF({ report, chartImages = {}, logoBase64 }) {
  const content = report.content || {};
  const coverage = content.coveragePeriod || report.coveragePeriod || {};

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Purple accent bar (fixed on every page) */}
        <View style={styles.headerBar} fixed />

        {/* Header (fixed on every page) */}
        <View style={styles.header} fixed>
          {logoBase64 && <Image src={logoBase64} style={{ height: 20 }} />}
          <Text style={{ fontSize: 8, color: BRAND.concrete }}>
            {report.title}{coverage.start ? ` | ${coverage.start} - ${coverage.end}` : ''}
          </Text>
        </View>

        {/* Footer with page numbers (fixed on every page) */}
        <View style={styles.footer} fixed>
          <Text style={{ fontSize: 7, color: BRAND.concrete }}>
            Generated by Social Command
          </Text>
          <Text
            style={{ fontSize: 7, color: BRAND.concrete }}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>

        {/* KPI Row */}
        {content.kpis?.length > 0 && (
          <View style={styles.kpiRow}>
            {content.kpis.map((kpi, i) => (
              <View key={i} style={styles.kpiCard}>
                <Text style={{ fontSize: 7, color: BRAND.concrete, marginBottom: 2 }}>
                  {kpi.label}
                </Text>
                <Text style={{ fontSize: 16, fontFamily: 'PlusJakartaSans', fontWeight: 600 }}>
                  {formatKPIValue(kpi)}
                </Text>
                {kpi.delta != null && (
                  <Text style={{
                    fontSize: 7,
                    marginTop: 2,
                    color: kpi.delta >= 0 ? '#22c55e' : BRAND.sienna,
                  }}>
                    {formatDelta(kpi.delta)}
                  </Text>
                )}
              </View>
            ))}
          </View>
        )}

        {/* Executive Summary */}
        {content.executiveSummary && (
          <View>
            <Text style={styles.sectionTitle}>Executive Summary</Text>
            <Text style={{ lineHeight: 1.6, fontSize: 10 }}>{content.executiveSummary}</Text>
          </View>
        )}

        {/* Charts (page break before each) */}
        {content.charts?.map((chart) => (
          <View key={chart.id} break>
            <Text style={styles.sectionTitle}>{chart.label}</Text>
            {chartImages[chart.id] ? (
              <Image src={chartImages[chart.id]} style={styles.chartImage} />
            ) : (
              <Text style={{ color: BRAND.concrete, fontSize: 9 }}>Chart unavailable</Text>
            )}
          </View>
        ))}

        {/* Sentiment Themes */}
        {content.sentimentThemes && (
          <View break>
            <Text style={styles.sectionTitle}>Sentiment Themes</Text>
            {(content.sentimentThemes.positive || []).map((t, i) => (
              <View key={`pos-${i}`} style={styles.sentimentCard}>
                <Text style={{ fontSize: 10, fontFamily: 'PlusJakartaSans', fontWeight: 600, marginBottom: 2 }}>
                  {t.theme}
                </Text>
                <Text style={{ fontSize: 8, color: BRAND.concrete }}>{t.detail}</Text>
                {t.volume != null && (
                  <Text style={{ fontSize: 7, color: '#22c55e', marginTop: 2 }}>{t.volume} mentions</Text>
                )}
              </View>
            ))}
            {(content.sentimentThemes.negative || []).map((t, i) => (
              <View key={`neg-${i}`} style={styles.sentimentCard}>
                <Text style={{ fontSize: 10, fontFamily: 'PlusJakartaSans', fontWeight: 600, marginBottom: 2 }}>
                  {t.theme}
                </Text>
                <Text style={{ fontSize: 8, color: BRAND.concrete }}>{t.detail}</Text>
                {t.volume != null && (
                  <Text style={{ fontSize: 7, color: BRAND.sienna, marginTop: 2 }}>{t.volume} mentions</Text>
                )}
              </View>
            ))}
            {(content.sentimentThemes.emerging || []).map((t, i) => (
              <View key={`em-${i}`} style={styles.sentimentCard}>
                <Text style={{ fontSize: 10, fontFamily: 'PlusJakartaSans', fontWeight: 600, marginBottom: 2 }}>
                  {t.topic}
                </Text>
                <Text style={{ fontSize: 8, color: BRAND.concrete }}>{t.signals}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Top Content */}
        {content.topContent?.length > 0 && (
          <View break>
            <Text style={styles.sectionTitle}>Top Content</Text>
            {content.topContent.map((item, i) => (
              <View key={i} style={{ marginBottom: 8, padding: 8, backgroundColor: BRAND.bone, borderRadius: 4 }}>
                <Text style={{ fontSize: 10, fontFamily: 'PlusJakartaSans', fontWeight: 600, marginBottom: 2 }}>
                  {item.title || item.postId}
                </Text>
                {item.whyItWorked && (
                  <Text style={{ fontSize: 8, color: BRAND.concrete, marginBottom: 2 }}>{item.whyItWorked}</Text>
                )}
                <Text style={{ fontSize: 7, color: BRAND.concrete }}>
                  {item.impressions != null ? `${item.impressions.toLocaleString()} impressions` : ''}
                  {item.engagementRate != null ? `  |  ${item.engagementRate}% engagement` : ''}
                </Text>
              </View>
            ))}
          </View>
        )}

        {/* Recommendations (page break before) */}
        {content.recommendations?.length > 0 && (
          <View break>
            <Text style={styles.sectionTitle}>Recommendations</Text>
            {content.recommendations.map((rec, i) => (
              <View key={i} style={styles.recommendationRow}>
                <Text style={{
                  fontSize: 8,
                  color: rec.priority === 'HIGH' ? BRAND.sienna : BRAND.concrete,
                  width: 40,
                }}>
                  [{rec.priority}]
                </Text>
                <View style={{ flex: 1 }}>
                  <Text style={{ fontSize: 10 }}>{rec.recommendation}</Text>
                  {rec.expectedImpact && (
                    <Text style={{ fontSize: 8, color: BRAND.concrete, marginTop: 2 }}>
                      Impact: {rec.expectedImpact}
                    </Text>
                  )}
                </View>
              </View>
            ))}
          </View>
        )}
      </Page>
    </Document>
  );
}

// ============================================================
// PREFETCH CHART IMAGES AS BASE64
// ============================================================

export async function prefetchChartImages(charts) {
  const images = {};
  for (const chart of charts || []) {
    if (!chart.imageUrl) continue;
    try {
      const res = await fetch(chart.imageUrl);
      const buf = Buffer.from(await res.arrayBuffer());
      images[chart.id] = `data:image/png;base64,${buf.toString('base64')}`;
    } catch (e) {
      images[chart.id] = null; // Graceful degradation
    }
  }
  return images;
}

// ============================================================
// RENDER REPORT PDF — Main entry point
// ============================================================

export async function renderReportPDF(report) {
  // Pre-fetch chart images as base64 for reliable embedding
  const charts = report.content?.charts || report.chartUrls || [];
  const chartImages = await prefetchChartImages(charts);

  // Read logo as base64 data URI
  let logoBase64 = null;
  try {
    const logoPath = path.join(process.cwd(), 'public/brand/logos/Figure_Logo_Purple.png');
    const logoBuf = fs.readFileSync(logoPath);
    logoBase64 = `data:image/png;base64,${logoBuf.toString('base64')}`;
  } catch (e) {
    // Logo file missing -- render without logo
  }

  // Render PDF to buffer
  const buffer = await renderToBuffer(
    <ReportPDF report={report} chartImages={chartImages} logoBase64={logoBase64} />
  );

  return buffer;
}
